Project:
  type: object
  properties:
    id:
      type: integer
      example: 1
    name:
      type: string
      example: Transaction  Platform
    team_id:
      type: integer
      example: 2
  required:
    - id
    - name
    - team_id