# coding: utf-8

"""
    Relay API

    Continuity handover dashboard for critical operations during pandemic disruption. Supports Operational Resilience Managers, Technology Team Leads, and Software Engineers in tracking task ownership, documentation readiness, and substitution capability. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.daily_log_entry import DailyLogEntry
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Baton(BaseModel):
    """
    Baton
    """ # noqa: E501
    id: StrictInt
    created_at: datetime
    updated_at: datetime
    project_id: StrictInt
    owner_id: StrictInt
    successor_ids: Optional[List[StrictInt]] = None
    title: StrictStr
    description: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    detailed_context: Optional[StrictStr] = None
    implementation_state: Optional[StrictStr] = None
    repo_link: Optional[StrictStr] = None
    branch_name: Optional[StrictStr] = None
    daily_logs: Optional[List[DailyLogEntry]] = None
    additional_resources: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "created_at", "updated_at", "project_id", "owner_id", "successor_ids", "title", "description", "status", "detailed_context", "implementation_state", "repo_link", "branch_name", "daily_logs", "additional_resources"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Baton from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in daily_logs (list)
        _items = []
        if self.daily_logs:
            for _item in self.daily_logs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['daily_logs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Baton from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "project_id": obj.get("project_id"),
            "owner_id": obj.get("owner_id"),
            "successor_ids": obj.get("successor_ids"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "detailed_context": obj.get("detailed_context"),
            "implementation_state": obj.get("implementation_state"),
            "repo_link": obj.get("repo_link"),
            "branch_name": obj.get("branch_name"),
            "daily_logs": [DailyLogEntry.from_dict(_item) for _item in obj.get("daily_logs")] if obj.get("daily_logs") is not None else None,
            "additional_resources": obj.get("additional_resources")
        })
        return _obj


